version: '3.8'
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: management:latest
    ports:
      - "8080:8080"
    environment:
      - REDIS_HOST=redis
    depends_on:
      - redis

  redis:
    image: redis:latest
